<?php

namespace Neartech\DevTool\Providers;

use Illuminate\Support\ServiceProvider;
use Neartech\DevTool\Console\Commands\CreateModuleCommand;

class DevToolServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {
        if (!$this->app->runningInConsole()) {
            return false;
        }

        $this->commands([
            CreateModuleCommand::class
        ]);

    }
}
